config/routes.rb
Graham::Application.routes.draw do
  resources :sp_earnings

  resources :notes

  resources :searches,
  :portfolios,
  :users,
  :transactions,
  :stocks,
  :splits,
  :eps

  match "defensive_stocks", :to => "stocks#defensive_stocks"
  match 'cheap_stocks', :to => "stocks#cheap_stocks"
  match "dear_stocks", :to => "stocks#dear_stocks"
  match 'defensive_buys', :to => "stocks#defensive_buys"
  match "pots", :to => "stocks#pots"
  match "cheap_profitables", :to => "stocks#cheap_profitables"
  match ":portfolio_id/new_transaction/:type", :to => "transactions#new"

  match ":data/sppe", :to => "data#sppe"

end

app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id          :integer(4)      not null, primary key
#  stock_id    :integer(4)
#  year        :integer(2)      default(2014)
#  pertains_to :enum([:K10, :Q1 default(:REPORTS)
#  note        :string(255)
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#

# enum options:
# enum EnumNotePERTAINS_TO { K10 = 1, Q10 = 2, REPORTS = 3, INCOME_REP = 4, NO_REV = 5, NO_INC = 6, NO_SHARES = 7, NO_EPS = 8, BALANCE_REP = 9, COVER_REP = 10, SHARES_OUTSTANDING = 11

class Note < ActiveRecord::Base
  belongs_to :stock
  validates_presence_of :stock_id

  # for handling enums
  def self.enum_columns
    # can be made dynamic wite columns_hash.each{ |c| c.sql_type}
    [:pertains_to]
  end

  def self.enum_field?(col_name)
    return enum_columns.include?(col_name)
  end

  def self.enum_options(col_name)
    enum_col = Note.columns_hash[col_name.to_s]
    ar = enum_col.limit
    ar = enum_string_to_values_array(enum_col.sql_type) if ar.class == Fixnum
    i = 0
    Hash[ar.map {|v| [v, i=i+1]}]
  end

  def self.enum_string_to_values_array(str)
    str_arr = str[6..-3].split(/','/)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notes }
    end
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    @note = Note.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @note }
    end
  end

  # GET /notes/new
  # GET /notes/new.json
  def new
    @note = Note.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @note }
    end
  end

  # GET /notes/1/edit
  def edit
    @note = Note.find(params[:id])
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(params[:note])

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render json: @note, status: :created, location: @note }
      else
        format.html { render action: "new" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.json
  def update
    @note = Note.find(params[:id])

    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :stock_id %><br />
    <%= f.collection_select(:stock_id, Stock.order(:ticker), :id, :ticker) %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :pertains_to %><br />
    <%= f.select(:pertains_to, Note.enum_options('pertains_to')) %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_field :note %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<h1>Listing notes</h1>

<table>
  <tr>
    <th>Stock</th>
    <th>Year</th>
    <th>Pertains to</th>
    <th>Note</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @notes.each do |note| %>
  <tr>
    <td><%= note.stock.ticker %></td>
    <td><%= note.year %></td>
    <td><%= note.pertains_to %></td>
    <td><%= note.note %></td>
    <td><%= link_to 'Show', note %></td>
    <td><%= link_to 'Edit', edit_note_path(note) %></td>
    <td><%= link_to 'Destroy', note, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Stock:</b>
  <%= @note.stock.ticker %>
</p>

<p>
  <b>Year:</b>
  <%= @note.year %>
</p>

<p>
  <b>Pertains to:</b>
  <%= @note.pertains_to %>
</p>

<p>
  <b>Note:</b>
  <%= @note.note %>
</p>


<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>