config/routes.rb
Graham::Application.routes.draw do
  resources :sp_earnings

  resources :notes

  resources :searches,
  :portfolios,
  :users,
  :transactions,
  :stocks,
  :splits,
  :eps

  match "defensive_stocks", :to => "stocks#defensive_stocks"
  match 'cheap_stocks', :to => "stocks#cheap_stocks"
  match "dear_stocks", :to => "stocks#dear_stocks"
  match 'defensive_buys', :to => "stocks#defensive_buys"
  match "pots", :to => "stocks#pots"
  match "cheap_profitables", :to => "stocks#cheap_profitables"
  match ":portfolio_id/new_transaction/:type", :to => "transactions#new"

  match ":data/sppe", :to => "data#sppe"

end

app/models/sp_earning.rb
# == Schema Information
#
# Table name: sp_earnings
#
#  id                :integer(4)      not null, primary key
#  calc_date         :date
#  list_file         :string(255)
#  num_included      :integer(4)
#  excluded_list     :string(255)
#  total_market_cap  :string(255)
#  public_market_cap :string(255)
#  total_earnings    :string(255)
#  market_pe         :decimal(15, 2)
#  index_price       :float
#  inferred_divisor  :integer(10)
#  divisor_earnings  :decimal(15, 2)
#  divisor_pe        :decimal(15, 2)
#  notes             :string(255)
#  created_at        :datetime        not null
#  updated_at        :datetime        not null
#  index_market_cap  :string(255)
#

class SpEarning < ActiveRecord::Base

  validates :calc_date, presence: true
  validates :list_file, presence: true
  validates :num_included, presence: true
  validates :total_market_cap, presence: true, format: { with: /\d*/,
    message: "only digits allowed" }
  validates :public_market_cap, presence: true, format: { with: /\d*/,
    message: "only digits allowed" }
  validates :total_earnings, presence: true, format: { with: /\d*/,
    message: "only digits allowed" }
  validates :market_pe, presence: true
  validates :index_price, presence: true
  validates :inferred_divisor, presence: true
  validates :divisor_earnings, presence: true
  validates :divisor_pe, presence: true


  def excluded
    # TODO: return a ruby array instead of a string
    excluded_list
  end

  def self.calc_earnings(list, save_to_db = false)
    # This method is not used in Graham application, so might be outdated
  end

  def self.get_index_price
    s = Stock.new
    s.get_price("","%5EGSPC")
  end

  def losing_percent
    (losers.to_f / num_included.to_f) * 100
  end

end

app/controllers/sp_earnings_controller.rb
class SpEarningsController < ApplicationController
  # GET /sp_earnings
  # GET /sp_earnings.json
  def index
    @sp_earnings = SpEarning.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sp_earnings }
    end
  end

  # GET /sp_earnings/1
  # GET /sp_earnings/1.json
  def show
    @sp_earning = SpEarning.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sp_earning }
    end
  end

  # GET /sp_earnings/new
  # GET /sp_earnings/new.json
  def new
    @sp_earning = SpEarning.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sp_earning }
    end
  end

  # GET /sp_earnings/1/edit
  def edit
    @sp_earning = SpEarning.find(params[:id])
  end

  # POST /sp_earnings
  # POST /sp_earnings.json
  def create
    @sp_earning = SpEarning.new(params[:sp_earning])

    respond_to do |format|
      if @sp_earning.save
        format.html { redirect_to @sp_earning, notice: 'Sp earning was successfully created.' }
        format.json { render json: @sp_earning, status: :created, location: @sp_earning }
      else
        format.html { render action: "new" }
        format.json { render json: @sp_earning.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sp_earnings/1
  # PUT /sp_earnings/1.json
  def update
    @sp_earning = SpEarning.find(params[:id])

    respond_to do |format|
      if @sp_earning.update_attributes(params[:sp_earning])
        format.html { redirect_to @sp_earning, notice: 'Sp earning was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sp_earning.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sp_earnings/1
  # DELETE /sp_earnings/1.json
  def destroy
    @sp_earning = SpEarning.find(params[:id])
    @sp_earning.destroy

    respond_to do |format|
      format.html { redirect_to sp_earnings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sp_earnings_helper.rb
module SpEarningsHelper
end

app/views/sp_earnings/_form.html.haml
= form_for @sp_earning do |f|
  - if @sp_earning.errors.any?
    #error_explanation
      %h2= "#{pluralize(@sp_earning.errors.count, "error")} prohibited this sp_earning from being saved:"
      %ul
        - @sp_earning.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :calc_date
    = f.date_select :calc_date
  .field
    = f.label :list_file
    = f.text_field :list_file
  .field
    = f.label :num_included
    = f.number_field :num_included
  .field
    = f.label :excluded_list
    = f.text_field :excluded_list
  .field
    = f.label :total_market_cap
    = f.text_field :total_market_cap
  .field
    = f.label :public_market_cap
    = f.text_field :public_market_cap
  .field
    = f.label :total_earnings
    = f.text_field :total_earnings
  .field
    = f.label :market_pe
    = f.text_field :market_pe
  .field
    = f.label :index_price
    = f.text_field :index_price
  .field
    = f.label :inferred_divisor
    = f.text_field :inferred_divisor
  .field
    = f.label :divisor_earnings
    = f.text_field :divisor_earnings
  .field
    = f.label :divisor_pe
    = f.text_field :divisor_pe
  .field
    = f.label :notes
    = f.text_field :notes
  .actions
    = f.submit 'Save'

app/views/sp_earnings/edit.html.haml
%h1 Editing sp_earning

= render 'form'

= link_to 'Show', @sp_earning
\|
= link_to 'Back', sp_earnings_path

app/views/sp_earnings/index.html.haml
%h1 Listing sp_earnings

%table
  %tr
    %th Calc date
    %th List file
    %th Size
    %th Excluded
    %th Total market cap
    %th Public market cap
    %th Total earnings
    %th Market pe
    %th Index price
    %th Inferred divisor
    %th Divisor earnings
    %th Divisor pe
    %th Notes
    %th


  - @sp_earnings.each do |sp_earning|
    %tr
      %td= sp_earning.calc_date
      %td= sp_earning.list_file
      %td= sp_earning.num_included
      %td= sp_earning.excluded_list.size
      %td= sp_earning.total_market_cap
      %td= sp_earning.public_market_cap
      %td= sp_earning.total_earnings
      %td= sp_earning.market_pe
      %td= sp_earning.index_price
      %td= sp_earning.inferred_divisor
      %td= sp_earning.divisor_earnings
      %td= sp_earning.divisor_pe
      %td= sp_earning.notes
      %td= link_to 'Show', sp_earning


%br

app/views/sp_earnings/new.html.haml
%h1 New sp_earning

= render 'form'

= link_to 'Back', sp_earnings_path

app/views/sp_earnings/show.html.haml
%p#notice= notice

%p
  %b Calc date:
  = @sp_earning.calc_date
%p
  %b List file:
  = @sp_earning.list_file
%p
  %b Size:
  = @sp_earning.size
%p
  %b Excluded list:
  = @sp_earning.excluded_list
%p
  %b Total market cap:
  = @sp_earning.total_market_cap
%p
  %b Public market cap:
  = @sp_earning.public_market_cap
%p
  %b Total earnings:
  = @sp_earning.total_earnings
%p
  %b Market pe:
  = @sp_earning.market_pe
%p
  %b Index price:
  = @sp_earning.index_price
%p
  %b Inferred divisor:
  = @sp_earning.inferred_divisor
%p
  %b Divisor earnings:
  = @sp_earning.divisor_earnings
%p
  %b Divisor pe:
  = @sp_earning.divisor_pe
%p
  %b Notes:
  = @sp_earning.notes

= link_to 'Edit', edit_sp_earning_path(@sp_earning)
\|
= link_to 'Back', sp_earnings_path