config/routes.rb
Graham::Application.routes.draw do
  resources :sp_earnings

  resources :notes

  resources :searches,
  :portfolios,
  :users,
  :transactions,
  :stocks,
  :splits,
  :eps

  match "defensive_stocks", :to => "stocks#defensive_stocks"
  match 'cheap_stocks', :to => "stocks#cheap_stocks"
  match "dear_stocks", :to => "stocks#dear_stocks"
  match 'defensive_buys', :to => "stocks#defensive_buys"
  match "pots", :to => "stocks#pots"
  match "cheap_profitables", :to => "stocks#cheap_profitables"
  match ":portfolio_id/new_transaction/:type", :to => "transactions#new"

  match ":data/sppe", :to => "data#sppe"

end

app/models/stock.rb
# == Schema Information
#
# Table name: stocks
#
#  id                 :integer(4)      not null, primary key
#  name               :string(255)
#  ticker             :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  dividends_per_year :integer(4)      default(4)
#  latest_price       :decimal(12, 6)
#  ttm_div            :decimal(10, 3)
#  yield              :decimal(6, 3)
#  listed             :boolean(1)      default(TRUE)
#  has_currant_ratio  :boolean(1)      default(TRUE)
#  mark               :string(255)
#  cik                :integer(4)
#  fiscal_year_end    :string(255)     default("")
#  company_type       :enum([:COMPANY, default(:COMPANY)
#  country            :string(255)
#  fy_same_as_ed      :boolean(1)      default(TRUE)
#  sub_sector_id      :integer(4)
#  ipo_year           :integer(4)
#

#enum EnumStockCOMPANY_TYPE { :COMPANY, :ROYALTY_TRUST, :REIT, :ASSET_MNGMT, :FINANCE, :PARTNERSHIP, :PIPELINE, :FOREIGN, :HOLDING, :INDUSTRY, :TECH, :PHARMA, :RETAIL ], :default => :COMPANY

class Stock < ActiveRecord::Base

  has_many :dividends
  has_many :notes
  has_many :eps, :dependent => :destroy
  has_many :numshares, :dependent => :destroy
  has_many :balance_sheets, :dependent => :destroy
  has_many :splits
  has_many :share_classes, foreign_key: "stock_id", class_name: "ShareClass"
  belongs_to :sub_sector

  accepts_nested_attributes_for :balance_sheets, :allow_destroy => true
  accepts_nested_attributes_for :eps, :allow_destroy => true

  validates_presence_of :ticker
  validates_uniqueness_of :ticker
  validates_presence_of :cik
  validates_uniqueness_of :cik

  include DataScraper
  include IConnection

  # for handling enums ------------------------------------------
  def self.enum_columns
    # can be made dynamic wite columns_hash.each{ |c| c.sql_type}
    [:company_type]
  end

  def self.enum_field?(col_name)
    return enum_columns.include?(col_name)
  end

  def self.enum_options(col_name)
    enum_col = Stock.columns_hash[col_name.to_s]
    ar = enum_col.limit
    ar = enum_string_to_values_array(enum_col.sql_type) if ar.class == Fixnum
    i = 0
    Hash[ar.map {|v| [v, i=i+1]}]
  end

  def self.enum_string_to_values_array(str)
    str_arr = str[6..-3].split(/','/)
  end
# end of enum methods code
#--------------------------------------------
  def self.get_stock_class_by_ticker(ticker)
    ShareClass.find_by_ticker(ticker)
  end

  def self.get_from_ticker(ticker)
    stock = find_by_ticker(ticker)
    if stock.nil?
      tk = ShareClass.find_by_ticker(ticker)
      stock = tk.stock if !tk.nil?
    end
    stock
  end


  #include MinMAx # adds min and max methods

  # 50 million dollars in 1972 adjusted for present day inflation
  # perhaps should also take in to account the growth of the market size itself?
  MIN_SALES = 500000000 # 500mil
  MIN_BV = 2500000000 # 2.5B

  # defining this hear, since for some reason it was not working if set from data_scraper
  YEAR = Time.new.year

#/ Valuation methods ---------------------------------------------------------

  # 1) Adequate size
  def big_enough?
    lbs = latest_balance_sheet
    lep = annual_eps_newest_first.first

    if !lbs.nil? && !lep.nil? && !lbs.book_val.nil? && !lep.revenue.nil?
      ret=( lep.revenue.to_i >= MIN_SALES || lbs.book_val >=MIN_BV)
    end

    if ret.nil? && !lbs.nil? && !lbs.assets_t.nil? && !lbs.liabilities_t.nil?
      ret = lbs.equity >= MIN_BV
    end

    ret.nil? ? false : ret
  end

  # 2) Finantialy strong
  # current assets > current liabilaties * 2   # For industrial
  # long term debt < current assets
  # debt < 2 * stock equity (at book value) # for public utilities
  def financialy_strong?
    bs = latest_balance_sheet
    if bs
      cr = bs.current_ratio
      alr = cr >= 2 if !cr.nil?
       alr = bs.assets_t >= bs.liabilities_t * 2 if alr.nil? && !bs.assets_t.nil? && !bs.liabilities_t.nil?
      dr = bs.debt < bs.assets_c if !bs.debt.nil? && !bs.assets_c.nil?
      dr = bs.debt < bs.assets_t if dr.nil? && !bs.debt.nil? && !bs.assets_t.nil?
    end
    (alr && dr) || false
  end

  # 3) Earnings stability
  # No loses in past 10 years
  def no_earnings_deficit?
    epss = annual_eps_newest_first.first(10)
    earning_deficit = epss.select{ |e| e.eps < 0 }
    earning_deficit.empty?
  end

  # 4) Continuos dividend record
  # This is pushed as the most important
  # Shold have uninterupted dividends over past 20 years
  # **Beware! does not include current year
  def continous_dividend_record?(years = 20)
    current_year = YEAR
    dg = dividends.group_by{ |d| d.date.year }

    (current_year - years..current_year - 1).each do |year|
      return false if dg[year].nil? || (!dg[year].nil? && dg[year].size < 2)
    end
    true
  end

  # 5) Earnings growth
  # This needs to be adjusted for stock splits/new offers/float ?
  # If every succeeding 3 year period is better than the previous
  def eps_growth?
    epss = annual_eps_newest_first
    if epss.size < 9
      epss = annual_eps_oldest_first
      growth = eps_avg(epss.first(max(epss.size / 2,3))) * 1.3 <= eps_avg(epss.last(3))
    else
      growth = eps_avg(epss[0..2]) > eps_avg(epss[3..5]) && eps_avg(epss[3..5]) > eps_avg(epss[6..8])
      if(epss.size >= 12 )
        growth = growth && (eps_avg(epss[6..8]) > eps_avg(epss[9..11]))
      end
    end
    growth
  end

  # 6) Moderate price (to earnings)
  # Upper price limit should be no more than:
  # 25 times average earnings over past 7 years, and
  # 20 times arerage earnings over past 1 year.
  # second criteria from page 182
  def price_limit
    # earning records do not go back far enough to compute price limit
    return 0 if historic_eps(7).nil? || ttm_eps.nil?

# || historic_eps(7).to_i == 0

    lim = min( historic_eps(7).to_f*25, ttm_eps*20 )
    min( historic_eps(3).to_f * 15, lim ) # second criteria from page 182
  end

  # 7) Moderate price (to book)
  def asset_to_price_ratio?
    price / ttm_eps * ( price / book_value_per_share ) <= 22.5
  end

  def price_to_limit_ratio
    return 0.0 if price_limit.nil? or price_limit == 0
    (price.to_f / price_limit.to_f)
  end

  def price_to_book_ratio
    return 0.0 if book_value_per_share.nil? or book_value_per_share == 0
    price.to_f / book_value_per_share.to_f
  end

  # Simplifiying to Joel Greenblat's 2 criteria
  # 1) High return on book - Earnings to Book
  # 2) Low price - Earnings to Market cap /PE
  # *) Buy all the best (a lot)


  # / End, Defensive buy breackdown---------------------------------------

  def cheap?
    return false if price.nil? or price_limit.nil?
    price < price_limit
  end

  # Set a price at wich a stock is overvalued to the point of concidering to sell it
  def valuation_limit
    return 1000000 if historic_eps(10).nil? || ttm_eps.nil?
    if historic_eps(10).to_i == 0 # historic eps returns string!
      ret = historic_eps(3)
      if ret.to_i == 0
        return 1
      else
        return ret * 28
      end
    end
    lim = max( historic_eps(10) * 26, ttm_eps*40 )
    if  historic_eps(3) == "Do not have 3 of earnings for #{ticker}"
      return 1000000
    end

    lim = max( historic_eps(3) * 28, lim ) # second criteria from page 182
    return 1000000 if lim.nil?
    return 1000000 if lim.to_i == 0
    lim.to_i
  end

  def overpriced?
    return false if price.nil?
    price > valuation_limit
  end

  def good_defensive_stock?
    big_enough? && financialy_strong? && no_earnings_deficit? && eps_growth? && continous_dividend_record? # dividents data does ont work?
  end

  def good_defensive_buy?
    good_defensive_stock? && cheap? #&& asset_to_price_ratio?
  end

  def bargain?
    (price * 1.5) < book_value_per_share #Not working in rails 3: 'price' is somehow morphed to a nokogiri::element  of some sort
    false
  end

  # This is from page 62 of "Inteligent investor":
  # "An industrial company's finances are not conservative unless the common stock (at book value) represents at least half of the total capitalization, including all bank debt."
  # currently understood to mean that book value is at least half of price
  def conservativly_financed?
    book_value_per_share * 2 >= price
  end


  #/ Data retreval methods ----------------------------------------------------

  def price
    @price ||= latest_price
  end

  def update_price
    p = get_price("",ticker)

    if !p.nil?
      update_attributes!(:latest_price => p)
      @price = p
    end
    share_classes.map(&:update_price)

    price
  end

  def update_price_if(num_days)
    update_price if updated_at < num_days.days.ago
    price
  end

  def newest_dividend
    dividends.sort_by{ |d| d.date }.last
  end

  def oldest_dividend
    dividends.sort_by{ |d| d.date }.first
  end

  def pays_dividends
    !dividends.empty? && newest_dividend.date > Date.today - 6.months
  end

  def update_dividends
    if newest_dividend.date < Date.today - (365/dividends_per_year).days
      # get (newest?) data
    end
  end

  #/ End /Data retrenal methods ------------------------------------------------

  def inflation_ratio_for(year)

    #please UPDATE!
    #Last updated: Jan 2019
    # uses inflation from every year, so that I don't need to update
    # Calculated as change in CPI, from jan 1 to jan 1, durring the given year,
    # i.e data for 2013 is for change ending jan 1 2014.
    # using "ALL Urban Consumers LESS Food & Energy (i.e. CORE inflation)
    # Source: https://research.stlouisfed.org/fred2/release?rid=10
    # Or: https://fred.stlouisfed.org/series/CPILFENS
    # Saved to file localy
    #
    ir = {
      2000 => 1.02581,
      2001 => 1.02735,
      2002 => 1.01917,
      2003 => 1.01149,
      2004 => 1.02169,
      2005 => 1.02174,
      2006 => 1.02573,
      2007 => 1.02439,
      2008 => 1.01763,
      2009 => 1.01816,
      2010 => 1.00804,
      2011 => 1.0223,
      2012 => 1.01893,
      2013 => 1.01717,
      2014 => 1.01606,
      2015 => 1.02216,

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def index
    @stocks = Stock.search(params[:search])
  end

  def bargains
    @bargains = Stock.all.select{ |s| s.bargain? }
  end

  def ncavs
    @stocks = Stock.all.select{ |s| s.latest_balance_sheet && s.ncav && s.translate_to_int(s.market_cap) != nil }
    @stocks = @stocks.select{ |s| s.ncav_ratio <= 1.1 }
  end

  def defensive_buys
    @stocks = Stock.all.select{ |s| s.good_defensive_buy? }
    @stocks = @stocks.sort_by{ |s| s.yield * -1}
  end

  def defensive_stocks
    @stocks = Stock.all.select{ |s| s.good_defensive_stock? }
    @stocks = @stocks.sort_by{ |s| s.price.to_f / s.price_limit.to_f }
  end

  def cheap_stocks
    @stocks = Stock.all.select{ |s| s.cheap? }
    @stocks = @stocks.select{ |s| s.price_limit > 1 }
    @stocks = @stocks.sort_by{ |s| s.price / s.price_limit }
  end

  def dear_stocks
    @stocks = Stock.all.select{ |s| s.overpriced? }
    @stocks = @stocks.select{ |s| s.valuation_limit < 1000000 }
    @stocks = @stocks.sort_by{ |s| s.ten_year_eps * -1 }
  end

  def pots
    @stocks = Stock.all.select{ |s| s.no_earnings_deficit? }
    @stocks = @stocks.select{ |s| s.dilution < 1.11 } # less than 10% dilution
    @stocks = @stocks.select{ |s| s.continous_dividend_record? } # has dividends
    @stocks = @stocks.sort_by{ |s| s.ten_year_eps }
  end

  def cheap_profitables
    @stocks = Stock.all.select{ |s| s.no_earnings_deficit? }
    @stocks = @stocks.select{ |s| s.dilution < 1.11 } # less than 10% dilution
    @stocks = @stocks.select{ |s| s.latest_balance_sheet.equity > 0 } # Positive book value
    @stocks = @stocks.select{ |s| s.financialy_strong?} # Ratios at least 2 to 1
    @stocks = @stocks.select{ |s| s.ten_year_eps < 20 && (s.price < s.ttm_eps*10 || s.price < s.historic_eps(3)*8) } # Cheap: defined as: less than 20 ten year PE and 8 3 year PE OR 10 current year PE
    @stocks = @stocks.sort_by{ |s| s.historic_eps(3) }
  end

  def show
    # This acceps both id and ticker to find the stock
    # wrap this in a helper or before filter
    id = params["id"]

    if (id.to_i > 0)
      @stock = Stock.find_by_ticker(id)
    else
      @stock = Stock.find_by_ticker(id)
      @stock = Stock.all.select{ |s| s.to_param == id }.first if @stock.nil?
    end

    @stock.update_price
    # realy all that is needed for constructing chart
    @earnings = @stock.annual_eps_oldest_first

    # 1) copy all numshare data into eps table in dev environment
    @numshare = @earnings.map{|s| [s.year,s.shares.to_i] }

    #adjust earnings.numshares for splits
    @stock.splits.each do |sp|
      @numshare.each do |ns|
        if sp.date.year > ns.first
          ns[1] = ( (sp.into.to_f / sp.base)*ns.last ).to_i
        end
      end
    end
    @numshare = @numshare.map{ |ns| ns.last }
    @income = @earnings.map{|s| s.net_income.to_i }
    @revenue = @earnings.map{|s| s.revenue.to_i }
    @notes = @stock.notes

    @ttm = @stock.ttm_earnings_record if !@stock.ttm_is_latest_annual?
    if !@ttm.nil?
      @income << @ttm.net_income.to_i
      @revenue << @ttm.revenue.to_i
      @numshare << @ttm.shares.to_i
    end

  end

  # GET /stocks/new
  # GET /stocks/new.xml
  def new
    @stock = Stock.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @stock }
    end
  end

  # GET /stocks/1/edit
  def edit
    @stock = Stock.find_by_ticker(params[:id])
  end

  # POST /stocks
  # POST /stocks.xml
  def create
    @stock = Stock.new(params[:stock])

    respond_to do |format|
      if @stock.save
        flash[:notice] = 'Stock was successfully created.'
        format.html { redirect_to(@stock) }
        format.xml  { render :xml => @stock, :status => :created, :location => @stock }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @stock.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /stocks/1
  # PUT /stocks/1.xml
  def update
     @stock = Stock.find_by_ticker(params[:id])

    if @stock.update_attributes(params[:stock])
      flash[:notice] = 'Stock was successfully updated.'
    end
    redirect_to(@stock)
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.xml
  def destroy
    @stock = Stock.find_by_ticker(params[:id])
    @stock.destroy

    respond_to do |format|
      format.html { redirect_to(stocks_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/stocks_helper.rb
module StocksHelper

  def add_data_link(form_builder)
    link_to_function 'Add data for another year', nil, do |page|
      form_builder.fields_for :balance_sheet, BalanceSheet.new, :child_index => 'NEW_RECORD' do |f|
        html = render(:partial => 'balance_sheet', :locals => { :ad_form => f })
        page << "$('finantials').insert({ bottom: '#{escape_javascript(html)}'.replace(/NEW_RECORD/g, new Date().getTime()) });"

      end
    end
  end

  def remove_data_link(form_builder)
    if form_builder.object.new_record?
      # If this is a new record, we can just remove the div from the dom
      link_to_function("remove", "$(this).up('.balance_sheet').remove();");
    else
      # However if it's a "real" record it has to be deleted from the database,
      # for this reason the new fields_for, accept_nested_attributes helpers give us _delete,
      # a virtual attribute that tells rails to delete the child record.
      ## form_builder.hidden_field(:delete) +
      ## link_to_function("remove", "$(this).up('.balance_sheet').hide(); $(this).previous().value = '1'")
    end
  end

  def add_earnings_link(form_builder)
    link_to_function 'Add Earnings data for another year', nil, do |page|
      form_builder.fields_for :ep, Ep.new, :child_index => 'NEW_RECORD' do |f|
        html = render(:partial => 'ep', :locals => { :e_form => f })
        page << "$('eps').insert({ bottom: '#{escape_javascript(html)}'.replace(/NEW_RECORD/g, new Date().getTime()) });"

      end
    end
  end

  def remove_earnings_link(form_builder)
    if form_builder.object.new_record?
      # If this is a new record, we can just remove the div from the dom
      link_to_function("remove", "$(this).up('.ep').remove();");
    else
      # However if it's a "real" record it has to be deleted from the database,
      # for this reason the new fields_for, accept_nested_attributes helpers give us _delete,
      # a virtual attribute that tells rails to delete the child record.
      ## form_builder.hidden_field(:delete) +
      ## link_to_function("remove", "$(this).up('.ep').hide(); $(this).previous().value = '1'")
    end
  end

  def yes_no(value)
    value == false ? "No" : "Yes"
  end

end

app/views/stocks/_dilution.html.haml
%li.list-group-item.row
  - if @stock.dilution(num) == 0
    %div.col-xs-12
      = "Not enough data to calulate dilution #{num} years back"
  - else 
    - if @stock.dilution(num) >= 1 
      %div.col-xs-9
        Over 
        =h num
        years, shares <span class='red'>DILUTED</span> by
      %span.bold.col-xs-3
        ="+ #{ ((@stock.dilution(num) - 1)* 100).to_i } % "
    - else
      %div.col-xs-9
        Over
        =h num
        years shares <span class='green'>REDUCED</span> by
      %span.bold.col-xs-3
        ="-  #{ ((1 - @stock.dilution(num)) * 100).to_i } % "

app/views/stocks/_yes_no.html.haml
- if @yn
  <span class="green">Yes</span>
- else
  <span class="red">No</span>

app/views/stocks/cheap_buys.html.haml
- num = 1
%table.stock-list
  %thead
    %th
      number
    %th
      ticker
    %th
      Yield
    %th
      Price
    %th
      Price limit
    %th
      Price/Limit
    %th
      Price/Book
    %th
      10 year P/E
  %tbody
    - @stocks.each do |stock|
      %tr
        %td
          = num
          - num = num + 1
        %td
          = link_to "#{stock.ticker}", stock_path(stock)
          = link_to "Dividends", stock.dividend_url
        %td
          = stock.yield
        %td
          = stock.price
        %td
          = stock.price_limit
        %td
          = short_float(stock.price.to_f / stock.price_limit.to_f)
        %td
          = short_float(stock.price.to_f / stock.book_value_per_share.to_f)
        %td
          = short_float(stock.ten_year_eps)

app/views/stocks/cheap_profitables.html.haml
- num = 1
%table.stock-list
  %thead
    %th
      number
    %th
      ticker
    %th
      Market Cap
    %th
      Dividend(year)
    %th
      Price/Limit
    %th
      1 year P/E
    %th
      3 year P/E
    %th
      10 year P/E
  %tbody
    - @stocks.each do |stock|
      %tr
        %td
          = num
          - num = num + 1
        %td
          = link_to "#{stock.ticker}", stock_path(stock)
          = link_to "Dividends", stock.dividend_url
        %td
          = stock.market_cap
        %td
          = stock.ttm_div
        %td
          = short_float( stock.price.to_f / stock.price_limit.to_f)
        %td
          = short_float( stock.price / stock.ttm_eps)
        %td
          = short_float( stock.price / stock.historic_eps(3))
        %td
          = short_float( stock.ten_year_eps )

app/views/stocks/dear_stocks.html.haml
- num = 1
%table.stock-list
  %thead
    %th
      number
    %th
      ticker
    %th
      Market Cap
    %th
      Price
    %th
      Price/Limit
    %th
      Price/Book
    %th
      10 year eps
  %tbody
    - @stocks.each do |stock|
      %tr
        %td
          = num
          - num = num + 1
        %td
          = link_to "#{stock.ticker}", stock_path(stock)
        %td
          = stock.market_cap
        %td
          = stock.price
        %td
          = short_float(stock.price.to_f / stock.price_limit.to_f)
        %td
          - if stock.book_value_per_share.nil? ||  stock.book_value_per_share == 0
            **
          - else
            = short_float(stock.price.to_f / stock.book_value_per_share.to_f)
        %td
          - a = stock.ten_year_eps
          = short_float(a)

app/views/stocks/defensive_buys.html.haml
- columns = [{:type => 'html', :class => "first"}, {:type => 'html'}, {:type => 'html'}, {:type => nil, :class => "last"}]
/ datatable(columns, {:sort_by => "[0, 'desc']", :processing => image_tag("spinner.gif") })

- num = 1
%table.datatable
  %thead
    %th
      number
    %th
      ticker
    %th
      Market Cap
    %th
      Dividend (year)
    %th
      Yield
    %th
      Price limit
    %th
      Price to book
    %th
      P/E (ttm)
    %th
      10 year PE

  %tbody
    - @stocks.each do |stock|
      %tr
        %td
          = num
          - num = num + 1
        %td
          = link_to "#{stock.ticker}", stock_path(stock)
          = link_to "Dividends", stock.dividend_url
        %td
          = stock.market_cap
        %td
          = stock.ttm_div
        %td
          = stock.yield
        %td
          = short_float(stock.price.to_f / stock.price_limit.to_f)
        %td
          = short_float(stock.price.to_f / stock.book_value_per_share.to_f)
        %td
          = short_float(stock.pe)
        %td
          = short_float(stock.ten_year_eps)

app/views/stocks/edit.html.haml
%h1
  Editing stock
= javascript_include_tag :defaults 
= form_for(@stock) do |stock_form| 
  - if @stock.errors.any? 
    #error_explanation
      = "#{pluralize(@stock.errors.count, "error")} prohibited this note from being saved:"
      - @stock.errors.full_messages.each do |msg| 
        = msg 
  %p
    = stock_form.label :name 
    = stock_form.text_field :name 
  %p
    = stock_form.label :ticker
    = stock_form.text_field :ticker
  %p
    = stock_form.label :company_type 
    = stock_form.select(:company_type, Stock.enum_options('company_type')) 
  #finantials
    - stock_form.fields_for :balance_sheets do |bs_form|
      = render :partial => 'balance_sheet', :locals => {:ad_form => bs_form, :stock_id => @stock.id }
    = add_data_link(stock_form) 
  %p
    #eps
      - stock_form.fields_for :eps do |e_form|
        = render :partial => 'ep', :locals => {:e_form => e_form, :stock_id => @stock.id }
      = add_earnings_link(stock_form) 
  %p
    = stock_form.submit 'Update'
= link_to 'Show', @stock 
= link_to 'Back', stocks_path

app/views/stocks/index.html.erb
<h1>Listing stocks</h1>


<%= form_tag stocks_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search]%>
    <%= submit_tag "Find", :name => nil %>
  </p>
<% end %>


<table>
  <tr>
    <th>Name</th>
    <th>Ticker</th>
  </tr>

<% @stocks.each do |stock| %>
  <tr>
    <td><%=h stock.name %></td>
    <td><%=h stock.ticker %></td>
    <td><%= link_to 'Show', :controller => "stocks", :action => "show" %></td>
    <td><%= link_to 'Edit',  :controller => "stocks", :action => "edit" %></td>
    <td><%= link_to 'Destroy', :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New stock', new_stock_path %>

app/views/stocks/pots.html.haml
- num = 1
%table.stock-list
  %thead
    %th
      number
    %th
      ticker
    %th
      Market Cap
    %th
      Dividend(year)
    %th
      Price
    %th
      Price limit
    %th
      Price/Limit
    %th
      Price/Book
    %th
      Dilution
    %th
      10 year P/E
  %tbody
    - @stocks.each do |stock|
      %tr
        %td
          = num
          - num = num + 1
        %td
          = link_to "#{stock.ticker}", stock_path(stock)
          = link_to "Dividends", stock.dividend_url
        %td
          = stock.market_cap
        %td
          = stock.ttm_div
        %td
          = stock.price
        %td
          = short_float( stock.price_limit )
        %td
          = #short_float(stock.price.to_f / stock.price_limit.to_f)
        %td
          = #short_float(stock.price.to_f / stock.book_value_per_share.to_f)
        %td
          = short_float( stock.dilution )
        %td
          = short_float( stock.ten_year_eps )

app/views/stocks/show.html.haml
%h1
  =h @stock.name
- if !@stock.listed
  .red
    #{@stock.ticker} is no longer listed for trade
- if ! @stock.sub_sector.nil?
  %h2
    = "#{@stock.sector.name} ||: #{@stock.sub_sector.name}"
%h2
  Ticker:
  =h @stock.ticker
  = link_to "on_google",
  "http://www.google.com/finance?q=#{@stock.ticker}"
- if @stock.has_multiple_share_classes?
  = "Has #{@stock.share_classes.size} share classes: #{@stock.share_classes.map{ |sc| [sc.sclass,sc.ticker] } }"
  = "Of which #{@stock.public_share_classes.size} are public"
%div.container
  %div.row
    %div.col-md-2
      Market cap: 
    %div.bold.col-md-2
      = is_to_s @stock.market_cap
  - if @stock.has_multiple_share_classes?
    %div.row
      %div.col-md-2
        Publicly traded cap: 
      %div.bold.col-md-2
        = is_to_s @stock.public_market_cap
  %div.row
    %div.col-md-2
      last price
    %div.bold.col-md-1
      = "$#{@stock.price}"
    %div.col-md-1
      = button_to("Update price", {:price => @stock.update_price }, :method => :put )

- if ! @stock.ttm_is_latest_annual?
  .red
    TTM data in last column   
  %div.row
    = "Year end is #{@stock.fiscal_year_end}"
- if !@notes.empty?
  .blue
    Stock has notes (displayed at bottom)


%div.container
  %div.row
    %div.col-md-10
      = render "stocks/earnings_chart"
    - if @stock.splits.size > 0
      %div.col-md-2
        = render "stocks/splits"

%div.container
  %div.row
    %div.col-md-5
      = render 'stocks/mydata'
    %div.col-md-5.col-md-offset-1
      = render "stocks/graham_data"
= render 'stocks/equity_chart'
= render 'stocks/be_table'
- if !@notes.empty?
  %table.stock-list
    %thead
      %th
        year
      %th
        pertains to
      %th
        note  
    %tbody
      - @notes.sort{ |a,b| b.year <=> a.year }.each do |n|
        %tr
          %td
            = n.year
          %td
            = n.pertains_to 
          %td
            = n.note

= link_to 'Back', stocks_path