config/routes.rb
Graham::Application.routes.draw do
  resources :sp_earnings

  resources :notes

  resources :searches,
  :portfolios,
  :users,
  :transactions,
  :stocks,
  :splits,
  :eps

  match "defensive_stocks", :to => "stocks#defensive_stocks"
  match 'cheap_stocks', :to => "stocks#cheap_stocks"
  match "dear_stocks", :to => "stocks#dear_stocks"
  match 'defensive_buys', :to => "stocks#defensive_buys"
  match "pots", :to => "stocks#pots"
  match "cheap_profitables", :to => "stocks#cheap_profitables"
  match ":portfolio_id/new_transaction/:type", :to => "transactions#new"

  match ":data/sppe", :to => "data#sppe"

end

app/models/search.rb
# == Schema Information
#
# Table name: searches
#
#  id              :integer(4)      not null, primary key
#  no_losses       :boolean(1)
#  divs            :boolean(1)
#  dilution        :float
#  created_at      :datetime
#  updated_at      :datetime
#  good_balance    :boolean(1)
#  book            :integer(4)
#  current_div     :boolean(1)
#  earning_growth  :boolean(1)
#  defensive_price :boolean(1)
#  big_enough      :boolean(1)
#  market_cap      :string(255)
#  sort_by         :string(255)
#  revenue         :string(255)
#  net_income      :string(255)
#  margin          :integer(4)
#  roe             :integer(4)
#

class Search < ActiveRecord::Base

# This method returns a list of stock per search request
  def stocks(sort_column = "pe_10",sort_direction = "desc")

    # this works very slowly
    # Maybe the best way to speed it up is to run the calculations, off line,
    # and then write the results to the db :)
    if @retrieved.nil?
       @stocks = Stock.where(listed: true)

      if defensive_price
        @stocks = @stocks.select{ |s| s.cheap? }
      end

      if !market_cap.nil?
        @stocks = @stocks.select{ |s| s.market_cap.to_i > market_cap.to_i }
      end

      if no_losses
        @stocks = @stocks.select{ |s| s.no_earnings_deficit? }
      end

      if good_balance
        @stocks = @stocks.select{ |s| s.financialy_strong? }
      end

      if divs
        @stocks = @stocks.select{ |s| s.continous_dividend_record? }
      end

      if current_div
        @stocks = @stocks.select{ |s| s.pays_dividends }
      end

      if dilution
        @stocks = @stocks.select{ |s| s.dilution(10) < (1+dilution/100) }
      end

      if book != 0
        if book > 0
          @stocks = @stocks.select{ |s| s.book_value > 0 }
        else
          @stocks = @stocks.select{ |s| s.book_value < 0 }
        end
      end

      if big_enough
        @stocks = @stocks.select{ |s| s.big_enough? }
      end

      if earning_growth
        @stocks = @stocks.select{ |s| s.eps_growth? }
      end

      has_nil_recs = true

      if !revenue.nil?
        @stocks.select!{ |s| ! s.ttm_earnings_record.nil? } if has_nil_recs
        has_nil_recs = false
        @stocks.select!{ |s| s.ttm_earnings_record.revenue.to_i > revenue.to_i }
      end

      if !net_income.nil?
        @stocks.select!{ |s| ! s.ttm_earnings_record.nil? } if has_nil_recs
        has_nil_recs = false
        @stocks.select!{ |s| s.ttm_earnings_record.net_income.to_i > net_income.to_i }
      end

      if !margin.nil?
        @stocks.select!{ |s| ! s.ttm_earnings_record.nil? } if has_nil_recs
        has_nil_recs = false
        @stocks.select!{ |s| s.ttm_earnings_record.net_income.to_f / s.ttm_earnings_record.revenue.to_i > (margin.to_f / 100) }
      end

      if !roe.nil?
        @stocks.select!{ |s| ! s.ttm_earnings_record.nil? } if has_nil_recs
        has_nil_recs = false
        @stocks.select!{ |s| s.ttm_earnings_record.net_income.to_f / s.book_value.to_i > (roe.to_f/100) }
      end

       @retrieved = 1
    end # end retrieving records

    # sort the results
    @backwards = 1
    if (sort_direction == "desc")
      @backwards = -1
    end

    case sort_column
    when "pe10"
     @stocks = @stocks.sort_by{ |s| (@backwards*s.ten_year_eps) }
    when "price_to_limit"
      @stocks = @stocks.sort_by{ |s| @backwards*s.price_to_limit_ratio }
    when "price_to_book"
      @stocks = @stocks.sort_by{ |s| @backwards*s.price_to_book_ratio }
    when "Market Cap"
      @stocks = @stocks.sort_by{ |s| (@backwards*s.market_cap) }
    when "pe"
      @stocks = @stocks.sort_by{ |s| @backwards*s.pe }
    when "price"
      @stocks = @stocks.sort_by{ |s| @backwards*s.price }
    when "max_pe"
      @stocks = @stocks.sort_by{ |s| @backwards*s.max_year_eps }
    else
      @stocks = @stocks.sort_by{ |s| s.ten_year_eps }
    end


  end #method stocks

end #class search

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  helper_method :sort_column, :sort_direction

  # GET /searches
  # GET /searches.xml
  def index
    @searches = Search.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @searches }
    end
  end

  # GET /searches/1
  # GET /searches/1.xml
  def show
    @search = Search.find(params[:id])

    @stocks = @search.stocks( sort_column, sort_direction )

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @search }
    end
  end

  # GET /searches/new
  # GET /searches/new.xml
  def new
    @search = Search.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @search }
    end
  end

  # GET /searches/1/edit
  def edit
    @search = Search.find(params[:id])
  end

  # POST /searches
  # POST /searches.xml
  def create
    @search = Search.new(params[:search])
    @params = params

    respond_to do |format|
      if @search.save
        format.html { redirect_to(@search, :notice => 'Search was successfully created.') }
        format.xml  { render :xml => @search, :status => :created, :location => @search }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @search.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /searches/1
  # PUT /searches/1.xml
  def update
    @search = Search.find(params[:id])

    respond_to do |format|
      if @search.update_attributes(params[:search])
        format.html { redirect_to(@search, :notice => 'Search was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @search.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.xml
  def destroy
    @search = Search.find(params[:id])
    @search.destroy

    respond_to do |format|
      format.html { redirect_to(searches_url) }
      format.xml  { head :ok }
    end
  end

private
  def sortable_columns
    ["pe", "pe10", "Market Cap", "max_pe", "price_to_book", "price_to_limit"]
  end

  def sort_column
    @sort_col = params[:column]
    sortable_columns.include?(params[:column]) ? params[:column] : "Market Cap"
  end

  def sort_direction
    @sort_dirc = params[:direction]
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "disc"
  end

end

app/helpers/searches_helper.rb
module SearchesHelper

  def sort_link(title, sort_name, updown)
    if(@sort_col==sort_name)
      updown = @sort_dirc == "asc" ? "desc" : "asc"
    end
    icon = updown == "desc" ? "glyphicon glyphicon-chevron-up" : "glyphicon glyphicon-chevron-down"
    link_to "#{title} <span class='#{icon}'></span>".html_safe, {column: sort_name, direction: updown}
  end
end

app/views/searches/edit.html.erb
<h1>Editing search</h1>

<%= form_for(@search) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :no_losses %><br />
    <%= f.check_box :no_losses %>
  </p>
  <p>
    <%= f.label :divs %><br />
    <%= f.check_box :divs %>
  </p>
  <p>
    <%= f.label :dilution %><br />
    <%= f.text_field :dilution %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<h1>Listing searches</h1>

<table>
  <tr>
    <th>No losses</th>
    <th>Divs</th>
    <th>Dilution</th>
  </tr>

<% @searches.each do |search| %>
  <tr>
    <td><%=h search.no_losses %></td>
    <td><%=h search.divs %></td>
    <td><%=h search.dilution %></td>
    <td><%= link_to 'Show', search %></td>
    <td><%= link_to 'Edit', edit_search_path(search) %></td>
    <td><%= link_to 'Destroy', search, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New search', new_search_path %>

app/views/searches/new.html.erb
<h1>New search</h1>

<%= form_for(@search ) do |f| %>
  <% @search.errors.full_messages.each do |msg| %>
    <p><%= msg %></p>
  <% end %>

  <p>
    (G1) Check that sales > 500 mil, and Book > 2.5B
    <%= f.label :sales %><br />
    <%= f.check_box :big_enough %>
  </p>

  <p>
    Market Cap larger than
    <%= f.label :market_cap %><br />
    <%= f.text_field :market_cap %>
  </p>

  <p>
    Revenue greater than
    <%= f.label :revenue %><br />
    <%= f.text_field :revenue %>
  </p>

  <p>
    Net Income greater than
    <%= f.label :net_income %><br />
    <%= f.text_field :net_income %>
  </p>

  <p>
    Margin greater than
    <%= f.label :margin %><br />
    <%= f.text_field :margin %>
  </p>

  <p>
    Return on Equity greater than
    <%= f.label :roe %><br />
    <%= f.text_field :roe %>
  </p>

  <p>
    (G2) Good current ration, and managable debt
    <%= f.check_box :good_balance %>
  </p>

  <p>
    <%= f.label :book_value_is %><br />
    <%= f.radio_button :book, 0, :checked => true %>
    <%= f.label :book, "any" %>
    <%= f.radio_button :book, 1 %>
    <%= f.label :book, "positive" %>
    <%= f.radio_button :book, -1 %>
    <%= f.label :book, "negative" %>
  </p>

  <p>
    (G3)
    <%= f.label :no_losses %><br />
    <%= f.check_box :no_losses %>
  </p>
  <p>
    (G4)
    <%= f.label :divs %><br />
    <%= f.check_box :divs %>
  </p>
  <p>
    <%= f.label :currently_paying_a_dividend %><br />
    <%= f.check_box :current_div %>
  </p>
  <p>
    <%= f.label :dilution %><br />
    <%= f.text_field :dilution %>
  </p>

  <p>
    (G5)
    <%= f.label :earnings_growth %><br />
    <%= f.check_box :earning_growth %>
  </p>

  <p>
    (G6)
    <%= f.label :defensive_price %><br />
    <%= f.check_box :defensive_price %>
  </p>

  <p>
    <%= f.label :sort_results_by %><br />
    <%= f.radio_button :sort_by, "pe10", :checked => true %>
    <%= f.label :sort, "pe10" %>
    <%= f.radio_button :sort_by, "price_to_limit" %>
    <%= f.label :sort, "price_to_limit" %>
    <%= f.radio_button :sort_by, "price_to_book" %>
    <%= f.label :sort, "price_to_book" %>
    <%= f.radio_button :sort_by, "market_cap" %>
    <%= f.label :sort, "market_cap" %>
    <%= f.radio_button :sort_by, "pe" %>
    <%= f.label :sort, "pe" %>
  </p>


  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', searches_path %>

app/views/searches/show.html.haml
%br
%h1
  Showing stocks with:
%br
- crit = 1

%p
  = "Params where #{@params.to_s}"
- if @search.big_enough
  %p
    %strong #{crit}. (G1) SALES more than 500 mil
    - crit = crit + 1

- if !@search.market_cap.nil?
  %p
    %strong #{crit}. MARKET CAP > #{ @search.market_cap.to_s }
    - crit = crit + 1

- if !@search.revenue.nil?
  %p
    %strong #{crit}. REVENUE > #{ @search.revenue }
    - crit = crit + 1

- if !@search.net_income.nil?
  %p
    %strong #{crit}. EARNINGS > #{ @search.net_income }
    - crit = crit + 1

- if !@search.margin.nil?
  %p
    %strong #{crit}. MARGIN > #{ @search.margin.to_s }
    - crit = crit + 1

- if !@search.roe.nil?
  %p
    %strong #{crit}. ROE > #{ @search.roe.to_s }
    - crit = crit + 1


- if @search.good_balance
  %p
    %strong #{crit}. (G2) BALANCE ratios are good
    - crit = crit + 1

- if @search.book != 0
  %p
    - str = "positive"
    - str = "negative" if @search.book < 0
    %strong #{crit}. BOOK VALUE is #{str} 
    - crit = crit + 1

- if @search.no_losses
  %p
    %strong #{crit}. (G3) NO LOSSES in past 10 years
    - crit = crit + 1

- if @search.divs
  %p
    %strong #{crit}. (G4) DIVIDEND consistant for 20 years
    - crit = crit + 1

- if @search.current_div
  %p
    %strong #{crit}. DIVIDEND is paid currently
    - crit = crit + 1

- if !@search.dilution.nil? #returning flase!?
  %p
    %strong #{crit}. DILUTION less than #{@search.dilution} % 
    - crit = crit + 1

- if @search.earning_growth
  %p
    %strong #{crit}. (G5) EARNINGS GROWTH
    - crit = crit + 1

- if @search.defensive_price
  %p
    %strong #{crit}. (G6) PRICE is below defensive limit
    - crit = crit + 1

%br
%br
%p
  = "Found total of #{@stocks.size} stocks, ordered by #{"10 year PE"}"

- num = 1
%table.stock-list.table-bordered.table-striped
  %thead
    %th
      number
    %th
      ticker
    %th
      = sort_link "Market Cap", "Market Cap", "desc"
    %th
      Price
    %th
      Price limit
    %th
      = sort_link "Price/limit", "price_to_limit", "asc"
    %th
      = sort_link "Price/Book", "price_to_book", "asc"
    %th
      = sort_link "10 year PE", "pe10", "asc"
    %th
      = sort_link "PE", "pe", "asc" 
    %th
      = sort_link "Max years PE", "max_pe", "asc"
    %th
      = "#Years of Earnings"
  %tbody
    - @stocks.each do |stock|
      %tr
        %td
          = num
          - num = num + 1
        %td
          = link_to "#{stock.ticker}", stock_path(stock)
          = link_to "Dividends", stock.dividend_url
        %td
          = "#{"%.2f" % (stock.market_cap.to_f / 1000000000)} Bil"
        %td
          = stock.price
        %td
          = short_float(stock.price_limit)
        %td
          = short_float( stock.price_to_limit_ratio) #stock.price.to_f / stock.price_limit.to_f)
        %td
          = short_float(stock.price_to_book_ratio) #.to_f / stock.book_value_per_share.to_f)
        %td
          = short_float(stock.ten_year_eps)
        %td
          = short_float(stock.pe)
        %td
          = short_float(stock.max_year_eps)
        %td
          = stock.max_eps_years
     